line-length = 100
target-version = "py39"

[lint]
select = ["F", "E"]
ignore = [
    "E501",  # Line too long (we have line-length as a soft guide)
    "E701",  # Multiple statements on one line (colon)
    "E731",  # Do not assign a lambda expression (sometimes useful)
]
